---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-data
  labels:
    app: events-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-data
  template:
    metadata:
      labels:
        app: events-data
    spec:
      containers:
      - name: events-data
<<<<<<< HEAD
        image: gcr.io/dtc-user107/internal-image:v1.0.0
=======
        image: gcr.io/dtc-user119/internal-image:v1.0.0
>>>>>>> d881da0132eb8e57971fa46fb7a77a9e24ecad19
        env:
        - name: PORT
          value: "8082"
        ports:
        - containerPort: 8082
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: events-data-service
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8082
  selector: 
    app: events-data
  type: ClusterIP